mod 'puppetlabs/stdlib', '4.25.1'
mod 'puppetlabs/concat', '4.2.1'
mod 'puppet/nginx', '0.13.0'
mod 'puppetlabs/inifile', '2.3.0'
mod 'puppet/letsencrypt',
  :git => 'https://github.com/voxpupuli/puppet-letsencrypt.git',
  :commit => '7ff199250c1693f65a4fef5fd96bfd8e3c75d40f'
